server: 
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://doblefactor.riu.net/api/v1/oauth/userinfo/


logging:
  level:
    root: INFO

